apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: team-1
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ghcr.io/sravyau09/hello-flux/github.com/sravyau09/hello-flux/apps/team-1/server # {"$imagepolicy": "team-1:server"}
        ports:
        - containerPort: 8080
